# server port
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    session:
      timeout: -1
      tracking-modes: cookie
      cookie:
        http-only: true
        secure: false

# data base
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container/demo01?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: jinseok
    password: 1234

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo01?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: jinseok
#    password: 1234

  # thymeleaf
  thymeleaf:
    cache: false

  # spring data jpa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

# ?? ??
#logging:
#  file:
#    name: ./logs/app.log
#  level:
#    root: error
#    org.hibernate: error

# ?? ??
logging:
  file:
    name: ./logs/app.log
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace


# ??? ?? ??
spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 100MB